packages:
  - shared
  - examples/**
  - .e2e
  - '!**/.vercel/**'
patchedDependencies:
  '@nuxtjs/tailwindcss': patches/@nuxtjs__tailwindcss.patch

overrides:
  "@nuxt/examples-ui": "workspace:*"
  "@nuxt/kit": "4.5.2"
  "@vue/shared": "3.5.41"
  nuxt: "4.1.0"
  vue: "3.5.41"

shellEmulator: true

allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  unrs-resolver: false
  vue-demi: false

minimumReleaseAgeExclude:
  - nuxt
  - nuxt-nightly
  - '@nuxt/*'
  - vue
  - '@vue/*'
