packages:
  - shared
  - examples/**
  - .e2e
  - '!**/.vercel/**'
ignoredBuiltDependencies:
  - esbuild
  - vue-demi
patchedDependencies:
  '@nuxtjs/tailwindcss': patches/@nuxtjs__tailwindcss.patch


overrides:
  "@nuxt/examples-ui": "workspace:*"
  "@nuxt/kit": "4.1.3"
  "@vue/shared": "3.5.33"
  nuxt: "4.1.0"
  vue: "3.5.33"
