packages:
  - shared
  - examples/**
  - .e2e
  - '!**/.vercel/**'
patchedDependencies:
  '@nuxtjs/tailwindcss': patches/@nuxtjs__tailwindcss.patch

overrides:
  "@nuxt/examples-ui": "workspace:*"
  "@nuxt/kit": "4.4.8"
  "@vue/shared": "3.5.39"
  nuxt: "4.4.7"
  vue: "3.5.39"

shellEmulator: true

allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
