name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# https://github.com/vitejs/vite/blob/main/.github/workflows/ci.yml
env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          cache: true
          install: false

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          cache: true
          install: false

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm typecheck
